apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-organization
spec:
  package: ghcr.io/hops-ops/aws-organization:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}

---

# skipDependencyResolution false would have named this hops-ops-aws-organizationrender
# so we need to match that format to avoid issues with the package name
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-aws-organizationrender
spec:
  package: ghcr.io/hops-ops/aws-organization_render:{{ .Values.version }}
  packagePullSecrets:
    - name: ghcr
  skipDependencyResolution: {{ .Values.skipDependencyResolution }}
