name: pr

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - '.github/workflows/on-pr.yaml'
      - '.gitops/**'
      - 'apis/**'
      - 'examples/**'
      - 'tests/**'
      - 'functions/**'
      - 'upbound.yaml'

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v1.1.0
    with:
      examples: |
        [
          { "example": "examples/organizations/individual.yaml" },
          { "example": "examples/organizations/individual.yaml", "observed_resources": "examples/observed-resources/individual/steps/1" },
          { "example": "examples/organizations/enterprise.yaml" },
          { "example": "examples/organizations/enterprise.yaml", "observed_resources": "examples/observed-resources/enterprise/steps/1" },
          { "example": "examples/organizations/enterprise.yaml", "observed_resources": "examples/observed-resources/enterprise/steps/2" },
          { "example": "examples/organizations/e2e-with-infrastructure.yaml" },
          { "example": "examples/organizations/e2e-with-infrastructure.yaml", "observed_resources": "examples/observed-resources/e2e-with-infrastructure/steps/1" },
          { "example": "examples/organizations/e2e-with-infrastructure.yaml", "observed_resources": "examples/observed-resources/e2e-with-infrastructure/steps/2" },
          { "example": "examples/organizations/e2e-with-infrastructure.yaml", "observed_resources": "examples/observed-resources/e2e-with-infrastructure/steps/3" }
        ]
      api_path: apis/organizations
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v1.1.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e-aws.yaml@v1.1.0
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      timeout-minutes: 30

  publish:
    needs:
      - validate
      - test
    uses: unbounded-tech/workflows-crossplane/.github/workflows/publish.yaml@v1.1.0
    secrets: inherit
    with:
      tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
